/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LMT
 */
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextArea;

public class Frame1 extends javax.swing.JFrame {

    // Tillader korresponerende indexer
    private HashMap<Character, Integer> ValuesMap;
    private List<Integer> EncryptedText;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        ValuesMap = new HashMap<>();
        EncryptedText = new ArrayList<>();
        TA2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA2 = new javax.swing.JTextArea();
        Krypter = new javax.swing.JButton();
        Dekrypter = new javax.swing.JButton();
        Clr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA3 = new javax.swing.JTextArea();
        Browse = new javax.swing.JButton();
        Hlp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Krypto");
        setResizable(false);

        jLabel1.setText("Input:");

        jLabel2.setText("Output:");

        TA1.setColumns(20);
        TA1.setRows(5);
        jScrollPane2.setViewportView(TA1);

        TA2.setColumns(20);
        TA2.setRows(5);
        jScrollPane3.setViewportView(TA2);

        Krypter.setText("Krypter");
        Krypter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KrypterActionPerformed(evt);
            }
        });

        Dekrypter.setText("Dekrypter");
        Dekrypter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DekrypterActionPerformed(evt);
            }
        });

        Clr.setText("Ryd");
        Clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClrActionPerformed(evt);
            }
        });

        jLabel3.setText("Navngiv / vælg fil:");

        TA3.setColumns(20);
        TA3.setRows(5);
        jScrollPane1.setViewportView(TA3);

        Browse.setText("Se Filer");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        Hlp.setText("Hjælp");
        Hlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HlpActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(Krypter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dekrypter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Browse)
                        .addGap(18, 18, 18)
                        .addComponent(Hlp)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)
                                .addGap(165, 165, 165)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Krypter)
                    .addComponent(Dekrypter)
                    .addComponent(Clr)
                    .addComponent(Browse)
                    .addComponent(Hlp))
                .addGap(179, 179, 179))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KrypterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KrypterActionPerformed
        // TODO add your handling code here:
        String UserInput = TA1.getText();

        for (int i = 0; i < UserInput.length(); i++) {
            //Validerer at en angivet Char er en key i ValuesMap
            if (!ValuesMap.containsKey(UserInput.charAt(i))) {
                //Tilegner tilfældige værdier til Chars i ValuesMap 
                Random rand = new Random();
                while (true) {
                    int RandomizedValue = rand.nextInt(Integer.MAX_VALUE);
                    if (!ValuesMap.containsValue(RandomizedValue)) {
                        ValuesMap.put(UserInput.charAt(i), RandomizedValue);
                        break;
                    }
                }

            }
        }
        //Validerer at der ikke forekommer en null værdi og kaster en undtagelse, hvis tilfældet skulle ske.
        for (int i = 0; i < UserInput.length(); i++) {
            int value = (ValuesMap.get(UserInput.charAt(i)) != null ? ValuesMap.get(UserInput.charAt(i)) : -1);

            if (value == -1) {
                throw new NullPointerException("Der blev fundet en ugyldig værdi i ValuesMap");
            }
            //Hvis ikke der er en null værdi, så taster den værdien ind i variablen EncryptedText.
            EncryptedText.add(value);
        }
        //Vi kører igennem for hvert index med en integer og tilføjer den til outputboksen.
        for (Object i : EncryptedText.toArray()) {
            TA2.append(i + " ");
        }

        try {
            System.out.println("Skriver tabel hos: " + System.getProperty("user.dir") + "\\" + TA3.getText() + ".enc");
            //FileOutputStream initialiseres, så vi har en forbindelse til filens lokalisation.
            FileOutputStream file = new FileOutputStream(System.getProperty("user.dir") + "\\" + TA3.getText() + ".enc");
            //ObjectOutputStream initialiseres, så vi kan skrive til vores fil, dvs. at ObjectOutputStream indsætter data.
            ObjectOutputStream output = new ObjectOutputStream(file);
            //Programmet skriver vores output objekt ind med alt den data der er til stede i ValuesMap.
            output.writeObject(ValuesMap);
            output.close(); //Forbindelse lukkes.
            file.close();   //Filen lukkes.
        } catch (IOException ex) {
        } //I tilfælde af uforudsete fejl, er der oprettet en undtagelseshåndtering. 

    }//GEN-LAST:event_KrypterActionPerformed

    private void DekrypterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DekrypterActionPerformed
        // TODO add your handling code here:

        //Skaber en variabel så man har adgang til den ønskede sti.
        File encyptionTable = new File(System.getProperty("user.dir") + "\\" + TA3.getText() + ".enc");

        if (encyptionTable.exists()) {
            try {
                //Se kommentar linje 185 og 187.
                FileInputStream file = new FileInputStream(encyptionTable);
                ObjectInputStream input = new ObjectInputStream(file);

                ValuesMap = (HashMap<Character, Integer>) input.readObject();
                //Se 191+192
                input.close();
                file.close();
                //Programmet håndterer potentielle undtagelser for IO eller ClaassNotFound.
            } catch (IOException | ClassNotFoundException ex) {
                TA2.append("Det du ønsker at dekryptere eksisterer ikke.");
            }

        }

        String[] UserInput = TA1.getText().split(" ");
        TA2.setText(null);

        //Udskriver dekrypteret data.
        for (int i = 0; i < UserInput.length; i++) {
            int value = Integer.parseInt(UserInput[i]);

            // "->" Lambda udtryk: https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html - Anonym klasse uden navn, enkeltmetode: Behandler funktionalitet som metode argument.
            ValuesMap.forEach((k, v) -> {
                if (v == value) {
                    TA2.append(k.toString());
                }
            }
              );
        }

    }//GEN-LAST:event_DekrypterActionPerformed

    private void ClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClrActionPerformed
        // TODO add your handling code here:
        TA1.setText(null);
        TA2.setText(null);
        TA3.setText(null);
    }//GEN-LAST:event_ClrActionPerformed

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        try {
            // TODO add your handling code here:
            //Åbner sted hvor filerne bliver gemt, så man kan holde styr på filerne.
            Desktop.getDesktop().open(new File(System.getProperty("user.dir")));
            //Undtagelseshåndtering
        } catch (IOException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BrowseActionPerformed

    private void HlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HlpActionPerformed
        // TODO add your handling code here:
        //Opretter en ny JFrame for brugervenlighed
        JFrame HLPFIL = new JFrame("Hjælpefil");
        HLPFIL.setVisible(true);
        HLPFIL.setResizable(false);
        HLPFIL.setSize(1280, 720);
        HLPFIL.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        HLPFIL.setLocationRelativeTo(null);

        JTextArea HLPAREA = new JTextArea();
        HLPAREA.setWrapStyleWord(rootPaneCheckingEnabled);
        HLPFIL.add(HLPAREA);
        String HLPTXT;
        HLPTXT = ("GENERELT: Programmet Krypto, er designet til at konvertere tekst til tal, for at kryptere ting så som kodeord.\n\n"
                + " Forneden følger en forklaring på de forskellige brugerfelter tilgængelige i programmet.\n\n"
                + "1. Input-feltet, angivet med teksten 'Input,' bruges til at skrive den tekst du ønsker at kryptere eller dekryptere.\n"
                + "2. Output-feltet, angivet med teksten 'Output,' er der hvor den krypterede eller dekrypterede tekst bliver fremvist.\n"
                + "3.Lager feltet, angivet med teksten Navngiv/Vælg fil, anvendes til to formål.\n"
                + "- Når du anvender 'Krypter' knappen vil programmet gemme en krypteret fil med information om den krypterede tekst som du har modtaget i outputfeltet.\n"
                + "- Det du skriver i feltet afgører hvilket navn filen har.\n"
                + "- Når du anvender 'Dekrypter' knappen, vil filen bruge den tekst du har sat i lager feltet.\n"
                + "- Det du skriver i feltet bruges til at finde den fil der indeholder den information du skal bruge til at få den tekst du har krypteret tilbage i ikke krypteret form.\n\n"
                + "Forneden følger en forklaring på de forskellige knapper tilgængelig i programmet.\n\n"
                + "1. 'Krypter' knappen bruges til at kryptere den tekst som på pågældende tispunkt står i Input-feltet.\n"
                + "2. 'Dekrypter' knappen bruges til at dekryptere den tekst som er gemt i den valgte fil og skriver det i output-feltet.\n"
                + "3. 'Ryd' knappen bruges til at fjerne alt teksten fra alle tekstfelter.\n"
                + "4. 'Se Filer' knappen bruges til at åbne det sted hvor de krypterede datafiler ligger.\n"
                + "5. 'Hjælp' knappen viser den information du kan læse om her frem./n");
        HLPAREA.append(HLPTXT);


    }//GEN-LAST:event_HlpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JButton Clr;
    private javax.swing.JButton Dekrypter;
    private javax.swing.JButton Hlp;
    private javax.swing.JButton Krypter;
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextArea TA2;
    private javax.swing.JTextArea TA3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
